### ISSUE TITLE
examples?

### ISSUE THREAD

**Issue by mikedfunk** [76design/76d-social-icons#1]
Can you post a page of examples?

**Comment by burlresearch** [comment]
After you clone the project - you should simply be able to open the file `index.html` in a browser to see all of the available social media icons.

![social icons](https://cloud.githubusercontent.com/assets/1835558/8299651/8cbedd10-1949-11e5-918b-1b054838cc1e.jpg)

**Comment by tappleby** [comment]
I also just added a link to the readme for the demo via [rawgit](https://rawgit.com/76design/76d-social-icons/master/index.html)
